### ISSUE TITLE
A click on Edit Course yields no effect 

### ISSUE THREAD

**Issue by sebbel** [Crowducate/crowducate-platform#113]
On develop branch when clicked on a course, I cannot use the Edit-Course Button. Nothing happens.
Being logged in or logged out yields the same result.

![crowducate](https://cloud.githubusercontent.com/assets/1940568/9780228/778e6db8-5786-11e5-9162-5eb34443caed.gif)

**Comment by sebbel** [comment]
**Session.set('editingCourseID', this._id);** inside https://github.com/Crowducate/crowducate-platform/blob/develop/client/templates/course/toolbar/edit-course.js seems to be the offending line. 
this._id is empty, thus not triggering the desired effect. Still working on a workaround and waiting if you get the same error, @brylie

**Comment by sebbel** [comment]
Apparently the whole "Add Lesson, Add Section" functionality is broken. I've successfully repaired the edit-course button with a dirty hack(https://gist.github.com/sbe/0d976ba5526d368c24d4), but I cannot add a section.

**Comment by brylie** [comment]
I have opened a pull request (#114) that resolves this issue.

**Comment by sebbel** [comment]
solved by #114
