### ISSUE TITLE
Default Branch

### ISSUE THREAD

**Issue by sebbel** [Crowducate/crowducate-platform#117]
Change default branch to develop, so the changes to develop branch get shown on the main page of the repo and repo appears as active as it is.

**Comment by Rahbaran** [comment]
yes, that's a good idea. @brylie ?

**Comment by brylie** [comment]
Sounds good to me.

On 14.09.2015 10:32, Amir Rahbaran wrote:

> yes, that's a good idea. @brylie https://github.com/brylie ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Crowducate/crowducate-platform/issues/117#issuecomment-139984558.

## 

Brylie Christopher Oxley

**Comment by Rahbaran** [comment]
Great, changed it.

**Comment by sebbel** [comment]
Wonderful!

Am Montag, 14. September 2015 schrieb Amir Rahbaran :
