### ISSUE TITLE
Update Meteor and all packages to the current version

### ISSUE THREAD

**Issue by sebbel** [Crowducate/crowducate-platform#124]
**As a developer, I would like to use the current version of all packages and of meteor so I have access to the latest functions and features.**

Please do this ASAP, before the gap gets too big.

**Comment by sebbel** [comment]
I have made progress with testing crowducate for 1.2.1,
there are no breaking changes and the application behaves like it should.
I will push a branch for testing and have it merged asap.

Also this issue should have precedence before the rest of all issues.

**Comment by sebbel** [comment]
I have issued a Pull Request #132 

@Crowducate/development Please review and merge.

**Comment by Rahbaran** [comment]
Merged! Thx @sbe!
