### ISSUE TITLE
Find out what the folder "newLayouts" is about

### ISSUE THREAD

**Issue by sebbel** [Crowducate/crowducate-platform#125]
Currently there is a folder inside the crowducate project in /client/templates named "newLayouts"

As a developer I would like to know what purpose folders have and what they do. Please find out what the newLayouts folder is about and rename it to suit its purpose.

**Comment by brylie** [comment]
@elnzv, what is the status of this folder? If I recall correctly, we were prototyping new layouts in this folder. We have since started a design-driven approach where we create SVG wireframes before writing HTML.

**Comment by 55** [comment]
@brylie, correct.
I think we can safely delete this folder.

**Comment by sebbel** [comment]
@brylie I am interested about the svg designing approach. 
I will delete the folder off develop for now.
