### ISSUE TITLE
crowducate-platform clone issue

### ISSUE THREAD

**Issue by aexonicarindam** [Crowducate/crowducate-platform#138]
I have cloned crowducate-platform from github. But I am getting old version of crowducate-platform.
http://quiz-aexonic.herokuapp.com/

There are any possibility to get http://crowducate.me/.

**Comment by brylie** [comment]
The version running at quiz-aexonic.heroluapp.com is the currennt version of Crowducate. 

The original version is no longer maintained, but [can still be downloaded](https://github.com/Crowducate/crowducate-platform/tree/1fb457e8ac7a2c8a28bc9618d96e74c76867609f).

**Comment by sebbel** [comment]
Hello aexonicarindam!

Thanks your interest in crowducate. It is a bit confusing I must admit. We
are currently rebuilding crowducate from the ground up and the version you
have deployed to your heroku is in fact the current version. We are in
great haste to add all the features from crowducate.me into the new version.

In the meantime, if you want to access the version that is running on
crowducate.me, you need to change to a different branch. Point a terminal
to crowducates root folder and issue
    git checkout master
That should get you the desired version!
We are happy to hear about your feedback :)

Best,
Sebastian

**Comment by aexonicarindam** [comment]
Hello Sbe,
   Please give me the branch url for crowducate.me's running version.

**Comment by sebbel** [comment]
I'm not so sure what you mean? You can either download the old, unmaintained version by clicking the link brylie has supplied or you can do git checkout master on the cloned version on your heroku (i think)

**Comment by aexonicarindam** [comment]
I am asking you that can I use running version of crowducate.me ??
If I then where will be available the running version of crowducate.me ??

**Comment by aexonicarindam** [comment]
Hello Sbe & Brylie,
  Can you tell me, when we can userunning version of crowducate.me ?
When are you uploaded the latest version of crowducate ?

**Comment by Rahbaran** [comment]
@aexonicarindam: The branch of "crowducate.me" is the **master** branch. 
1. Click on the link which Brylie provided
2. Read the read.me (most important part of read.me: use meteor 0.80)
3. in the upper right of the link, there's the "download zip" button

 let us know if this helped.

**Comment by aexonicarindam** [comment]
Thanks.
