### ISSUE TITLE
The tags donot display a list of courses with the given tag

### ISSUE THREAD

**Issue by Saumik** [Crowducate/crowducate-platform#143]
I just set up the latest version of crowducate-platform on my mac. Tried to add a tag "cartoon", and created multiple courses with the tag. But, the link [http://localhost:3000/tag/cartoon] is empty.

**Comment by sebbel** [comment]
Hej @Saumik, 
Thanks for trying out crowducate :)
The tag feature is currently broken as stated in #106. The tags arrive in the respecting mongo document, but are not properly shown on the frontpage.
I will have it as a priority task for this weekend.

If you know how to fix it yourself, feel free to submit a pull request :)

**Comment by sebbel** [comment]
Haven't gotten around to take a look at it.

**Comment by sebbel** [comment]
Started work on this via #144

**Comment by sebbel** [comment]
hey @Saumik, we have fixed the tags feature. It should work as expected now :)
