### ISSUE TITLE
porting to meteor 1.0

### ISSUE THREAD

**Issue by dcsan** [Crowducate/crowducate-platform#23]
this is a very cool project, but currently its based on an old meteor. 
I'd like to help bring it up to 1.0, but there are [quite a few custom packages](https://github.com/Crowducate/crowducate.me/blob/master/.meteor/packages) that haven't been brought up to/don't exist for 1.0

@DerMambo if you could suggest the best way to migrate that would be very helpful..

we could just add whatever minimum is needed and republish the packages for 1.0 - if there are no other changes this is the quickest.
but there are some core pieces of the infra that maybe better switched out before building any new features? eg I use autoform rather than "mambo-forms". But porting the UI to a different forms package, Schema validation etc seems like a major undertaking?
mambo forms hasn't been touched for 4 months, does it work with latest router etc?

additionally the auth related stuff looks very out of date, but I'm loath to mess around with those type of packages. they always take ages to get working nicely...

@yauh any thoughts? 

```
# Packages by Manuel Schoebel
mambo-authenticate
ms-validator
ms-markdown-editor
basic-auth
mambo-forms

## non-critical:
ms-google-analytics
ms-seo
common-helpers
notify
bootstrap-tabs
moment

```

comparing with
https://atmospherejs.com/manuelschoebel

**Comment by Rahbaran** [comment]
We decided the best approach is to write Crowducate from scratch: https://github.com/meteorcrowd/crowducate-next When the new version is ready (won't take long, if the process continues), the issues reg. porting to 1.0 will be closed.

**Comment by brylie** [comment]
We are now conducting development in the [crowducate-platform:develop](https://github.com/Crowducate/crowducate-platform/tree/develop) branch. Closing this issue, as the 1.0 development started from scratch.
