### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by mhshakouri** [Crowducate/crowducate-platform#36]
I think internationalization is great to enable users establish free online schools for their countries.

**Comment by Rahbaran** [comment]
I fully agree @mhshakouri . What particular steps for internationalization are in your mind (e.g. support for different alphabets,  having the main texts of the homepage available in different languages, etc. etc.)?

**Comment by mhshakouri** [comment]
well since the source is free, first you've to make sure that if the users like me and you , you a pro, me a beginner meteorite!, use it, they give free services to others with such tools. 
The same like you, I'm from Iran, I really wanted to contact you too. I've a plan in mind, of giving a service to people in here with tools like your crowducate and weworkmeteor core and also telesc.pe , I needed your permission too ;)
now that you're here it's better!

By internationalization, I mean the total UI language users are in contact, to make it serve-able for people with different languages.
I noted somewhere there was point on i18n on the road map on hackpad I guess.

**Comment by Rahbaran** [comment]
Yes, you are right. I think you mean this part: https://hackpad.com/Crowducate-Roadmap-Ideas-ATAX9ZTodoe#:h=Language-support-%28i18n,-l10n%29

If you have general questions about crowducate, you also contant me (choose your favourite option from http://amir-rahbaran.com/ :) )

Also any feedback on many more hackpads is appreciated: http://crowducate.hackpad.com/

**Comment by dcsan** [comment]
which i18n library are you thinking to use?

**Comment by mhshakouri** [comment]
I'll contact you soon Amir,
at least I can say I need too.
I'm not like you guys , pro's, but I can suggest tap:i18n , it felt great while I saw the structure beyond telesc.pe and the way they used tap:i18n

**Comment by brylie** [comment]
[tap:i18n](https://github.com/TAPevents/tap-i18n) is worth considering. We are [planning](https://github.com/Crowducate/crowducate-next/issues/18) to start building the i18n foundation in [crowducate-next](https://github.com/Crowducate/crowducate-next) during the next sprint (starting Monday, March 9th.)

**Comment by brylie** [comment]
I am closing this issue, since we have added an i18n platform and translated the UI into [four languages (in addition to English)](https://github.com/Crowducate/crowducate-platform/blob/develop/server/mfAll.js).

Any subsequent translation efforts should be tracked in separate issue(s).

**Comment by Rahbaran** [comment]
@mhshakouri Here's the whole translation in a Google Doc. Might move to Hackpad soon. 
https://docs.google.com/spreadsheets/d/1h-OpSpqIb-mIv21hI0c6dAbJr0AGSfmfkNJCnZA3Q6I
