### ISSUE TITLE
Crowducate defaults to German

### ISSUE THREAD

**Issue by sbe** [Crowducate/crowducate-platform#40]
Should default to English.

Can someone check if he can reproduce?

**Comment by Rahbaran** [comment]
hm ... when I'm in the dev branch I even don't see the German option at all.

**Comment by sbe** [comment]
same here!

Am Montag, 1. Juni 2015 schrieb Amir Rahbaran :

**Comment by Rahbaran** [comment]
hm ... maybe @brylie  knows the answer?

**Comment by brylie** [comment]
I think the localization package detects your browser default language and renders the corresponding translation, if available.

**Comment by Rahbaran** [comment]
As mentioned, it was not even possible to choose German. However, @sbe pointed to this file: https://github.com/Crowducate/crowducate-platform/blob/develop/client/templates/layouts/header/languageSelection/languageSelection.html 

Changed the file, tested and now it works.
